Coerce color to RGB before converting to hex value
If you create a new `HueColor` instance using the `fromHsb(...)` method,
the color's rgb properties will be null. `.toHex()` implicitly assumes
those fields are valid numbers. Consequently, if you try to convert an
HSB color to a hex value you'll get a surprising error:

```
TypeError: Cannot read property 'toString' of null
```

The solution was as simple as using the `.toRgb()` method.